CREATE TABLE company_overview (
                                  ticker VARCHAR(10) PRIMARY KEY,
                                  name VARCHAR(255),
                                  description VARCHAR,
                                  country VARCHAR(20),
                                  sector VARCHAR(50),
                                  industry VARCHAR(50),
                                  address VARCHAR(255)
);

CREATE TABLE income_statement (
                                  id VARCHAR(30) PRIMARY KEY NOT NULL ,
                                  ticker VARCHAR(10) REFERENCES company_overview(ticker) ON DELETE CASCADE NOT NULL ,
                                  type VARCHAR(10) NOT NULL,
                                  fiscaldateending DATE NOT NULL ,
                                  reportedcurrency VARCHAR(10) NOT NULL ,
                                  grossprofit BIGINT,
                                  totalrevenue BIGINT,
                                  costofrevenue BIGINT,
                                  costofgoodsandservicessold BIGINT,
                                  operatingincome BIGINT,
                                  sellinggeneralandadministrative BIGINT,
                                  researchanddevelopment BIGINT,
                                  operatingexpenses BIGINT,
                                  investmentincomenet BIGINT,
                                  netinterestincome BIGINT,
                                  interestincome BIGINT,
                                  interestexpense BIGINT,
                                  noninterestincome BIGINT,
                                  othernonoperatingincome BIGINT,
                                  depreciation BIGINT,
                                  depreciationandamortization BIGINT,
                                  incomebeforetax BIGINT,
                                  incometaxexpense BIGINT,
                                  interestanddebtexpense BIGINT,
                                  netincomefromcontinuingoperations BIGINT,
                                  comprehensiveincomenetoftax BIGINT,
                                  ebit BIGINT,
                                  ebitda BIGINT,
                                  netincome BIGINT
);

CREATE TABLE balance_sheet (
                               id VARCHAR(30) PRIMARY KEY NOT NULL ,
                               ticker VARCHAR(10) REFERENCES company_overview(ticker) ON DELETE CASCADE NOT NULL ,
                               fiscaldateending DATE,
                               type VARCHAR(10),
                               reportedcurrency VARCHAR(10),
                               totalassets BIGINT,
                               totalcurrentassets BIGINT,
                               cashandcashequivalentsatcarryingvalue BIGINT,
                               cashandshortterminvestments BIGINT,
                               inventory BIGINT,
                               currentnetreceivables BIGINT,
                               totalnoncurrentassets BIGINT,
                               propertyplantequipment BIGINT,
                               accumulateddepreciationamortizationppe BIGINT,
                               intangibleassets BIGINT,
                               intangibleassetsexcludinggoodwill BIGINT,
                               goodwill BIGINT,
                               investments BIGINT,
                               longterminvestments BIGINT,
                               shortterminvestments BIGINT,
                               othercurrentassets BIGINT,
                               othernoncurrentassets BIGINT,
                               totalliabilities BIGINT,
                               totalcurrentliabilities BIGINT,
                               currentaccountspayable BIGINT,
                               deferredrevenue BIGINT,
                               currentdebt BIGINT,
                               shorttermdebt BIGINT,
                               totalnoncurrentliabilities BIGINT,
                               capitalleaseobligations BIGINT,
                               longtermdebt BIGINT,
                               currentlongtermdebt BIGINT,
                               longtermdebtnoncurrent BIGINT,
                               shortlongtermdettotal BIGINT,
                               othercurrentliabilities BIGINT,
                               othernoncurrentliabilities BIGINT,
                               totalshareholderequity BIGINT,
                               treasurystock BIGINT,
                               retainedearnings BIGINT,
                               commonstock BIGINT,
                               commonstocksharesoutstanding BIGINT
);

CREATE TABLE cash_flow (
                           id VARCHAR(30) NOT NULL PRIMARY KEY,
                           ticker VARCHAR(10) REFERENCES company_overview(ticker) ON DELETE CASCADE NOT NULL,
                           fiscaldateending DATE,
                           type VARCHAR(10),
                           reportedcurrency VARCHAR(10),
                           operatingcashflow BIGINT,
                           paymentsforoperatingactivities BIGINT,
                           proceedsfromoperatingactivities BIGINT,
                           changeinoperatingliabilities BIGINT,
                           changeinoperatingassets BIGINT,
                           depreciationdepletionandamortization BIGINT,
                           capitalexpenditures BIGINT,
                           changeinreceivables BIGINT,
                           changeininventory BIGINT,
                           profitloss BIGINT,
                           cashflowfrominvestment BIGINT,
                           cashflowfromfinancing BIGINT,
                           proceedsfromrepaymentsofshorttermdet BIGINT,
                           paymentsforrepurchaseofcommonstock BIGINT,
                           paymentsforrepurchaseofequity BIGINT,
                           paymentsforrepurchaseofpreferredstock BIGINT,
                           dividendpayout BIGINT,
                           dividendpayoutcommonstock BIGINT,
                           dividendpayoutpreferredstock BIGINT,
                           proceedsfromissuanceofcommonstock BIGINT,
                           proceedsfromissuanceoflongtermdetandcapitalsecuritiesnet BIGINT,
                           proceedsfromissuanceofpreferredstock BIGINT,
                           proceedsfromrepurchaseofequity BIGINT,
                           proceedsfromsaleoftreasurystock BIGINT,
                           changeincashandcashequivalents BIGINT,
                           changeinexchangerate BIGINT,
                           netincome BIGINT
);